[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --themesDir themes"

[build.environment]
  HUGO_VERSION = "0.92.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "http://rsjeni.github.io/me/"
