[build]
  publish = " http://rsjeni.github.io/me/public"
  command = "cd  http://rsjeni.github.io/me/ && hugo --themesDir themes"

[build.environment]
  HUGO_VERSION = "0.92.0"
  HUGO_THEME = "hugo-hero-theme"
  HUGO_BASEURL = " http://rsjeni.github.io/me/"